
services:
  kk_app:
    build: .
    container_name: kk_php82_mysql57
    ports:
      - "8083:80"
    volumes:
      #      - ./www:/var/www/html
      - ./:/var/site
      - ./apache-logs:/var/log/apache2  # монтируем директорию на хосте для логов
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.44
    container_name: kk_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kc
      MYSQL_USER: kc
      MYSQL_PASSWORD: kc
    ports:
      - "3312:3306"
    volumes:
      - D:\work\kk\docker_db:/var/lib/mysql
