CREATE TABLE IF NOT EXISTS properties (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    code VARCHAR(20) UNIQUE NOT NULL,
    name VARCHAR(255),
    type ENUM('house', 'apartment', 'office') NOT NULL,
    status ENUM('ready', 'new', 'shared') NOT NULL DEFAULT 'ready',
    deal_type ENUM('sale', 'rent') NOT NULL,
    price DECIMAL(12, 2) NOT NULL,
    old_price DECIMAL(12, 2),
    currency VARCHAR(3) DEFAULT 'EUR',
    city VARCHAR(100) NOT NULL,
    municipality VARCHAR(100),
    address VARCHAR(255),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    rooms INT,
    bedrooms INT,
    bathrooms INT,
    area DECIMAL(10, 2),
    lot_area DECIMAL(10, 2),
    floors INT,
    current_floor INT,
    year_built INT,
    garage BOOLEAN DEFAULT FALSE,
    parking BOOLEAN DEFAULT FALSE,
    elevator BOOLEAN DEFAULT FALSE,
    terrace BOOLEAN DEFAULT FALSE,
    basement BOOLEAN DEFAULT FALSE,
    attic BOOLEAN DEFAULT FALSE,
    heating BOOLEAN DEFAULT FALSE,
    cooling BOOLEAN DEFAULT FALSE,
    furnished BOOLEAN DEFAULT FALSE,
    security BOOLEAN DEFAULT FALSE,
    garden BOOLEAN DEFAULT FALSE,
    view_type VARCHAR(100),
    last_renovation INT,
    is_active BOOLEAN DEFAULT TRUE,
    view_count INT DEFAULT 0,
    features JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_code (code),
    INDEX idx_type (type),
    INDEX idx_deal_type (deal_type),
    INDEX idx_city (city),
    INDEX idx_price (price),
    INDEX idx_active (is_active),
    INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;