<?php

/**
 * This file is auto-generated by generate-command-map.php.
 * Do not edit manually.
 */

declare(strict_types=1);

return [
    \App\Feature\Admin\Auth\Api\LoginCheck\AdminAuthLoginCheckApiCommand::class => \App\Feature\Admin\Auth\Api\LoginCheck\AdminAuthLoginCheckApiHandler::class,
    \App\Feature\Admin\Auth\Api\Logout\AdminAuthLogoutApiCommand::class => \App\Feature\Admin\Auth\Api\Logout\AdminAuthLogoutApiHandler::class,
    \App\Feature\Admin\Auth\View\LoginForm\AdminAuthLoginFormViewCommand::class => \App\Feature\Admin\Auth\View\LoginForm\AdminAuthLoginFormViewHandler::class,
    \App\Feature\Admin\Layout\View\HomePage\AdminLayoutHomePageViewCommand::class => \App\Feature\Admin\Layout\View\HomePage\AdminLayoutHomePageViewHandler::class,
];
